"""MVP-38 — Local Research Remediation Evidence Tracker."""

from __future__ import annotations

from hunter.remediation_evidence.engine import build_remediation_evidence_report
from hunter.remediation_evidence.models import (
    FORBIDDEN_REMEDIATION_EVIDENCE_TERMS,
    REMEDIATION_EVIDENCE_VERSION,
    RemediationBacklogItemRef,
    RemediationEvidenceConfig,
    RemediationEvidenceCoverageResult,
    RemediationEvidenceCoverageState,
    RemediationEvidenceDataQuality,
    RemediationEvidenceInput,
    RemediationEvidenceIssue,
    RemediationEvidenceIssueType,
    RemediationEvidenceLink,
    RemediationEvidenceLinkType,
    RemediationEvidenceReasonCode,
    RemediationEvidenceRecord,
    RemediationEvidenceRecordState,
    RemediationEvidenceReport,
    RemediationEvidenceReviewOutcome,
    RemediationReviewRecord,
    RemediationEvidenceSafetyFlags,
    RemediationEvidenceSeverity,
    RemediationEvidenceState,
    has_unsafe_remediation_evidence_content,
)
from hunter.remediation_evidence.writer import (
    DEFAULT_CSV_PATH,
    DEFAULT_JSON_PATH,
    DEFAULT_MD_PATH,
    atomic_write_csv_remediation_evidence_report,
    atomic_write_json_remediation_evidence_report,
    atomic_write_markdown_remediation_evidence_report,
    remediation_evidence_report_to_csv_text,
    remediation_evidence_report_to_dict,
    remediation_evidence_report_to_json_text,
    remediation_evidence_report_to_markdown_text,
    write_remediation_evidence_report,
)

__all__ = [
    "DEFAULT_CSV_PATH",
    "DEFAULT_JSON_PATH",
    "DEFAULT_MD_PATH",
    "FORBIDDEN_REMEDIATION_EVIDENCE_TERMS",
    "REMEDIATION_EVIDENCE_VERSION",
    "RemediationBacklogItemRef",
    "RemediationEvidenceConfig",
    "RemediationEvidenceCoverageResult",
    "RemediationEvidenceCoverageState",
    "RemediationEvidenceDataQuality",
    "RemediationEvidenceInput",
    "RemediationEvidenceIssue",
    "RemediationEvidenceIssueType",
    "RemediationEvidenceLink",
    "RemediationEvidenceLinkType",
    "RemediationEvidenceReasonCode",
    "RemediationEvidenceRecord",
    "RemediationEvidenceRecordState",
    "RemediationEvidenceReport",
    "RemediationEvidenceReviewOutcome",
    "RemediationReviewRecord",
    "RemediationEvidenceSafetyFlags",
    "RemediationEvidenceSeverity",
    "RemediationEvidenceState",
    "atomic_write_csv_remediation_evidence_report",
    "atomic_write_json_remediation_evidence_report",
    "atomic_write_markdown_remediation_evidence_report",
    "build_remediation_evidence_report",
    "has_unsafe_remediation_evidence_content",
    "remediation_evidence_report_to_csv_text",
    "remediation_evidence_report_to_dict",
    "remediation_evidence_report_to_json_text",
    "remediation_evidence_report_to_markdown_text",
    "write_remediation_evidence_report",
]
