"""Public API for hunter.run_orchestrator package.

MVP-30 — Local Research Run Orchestrator.

All exports are deterministic, local, and research-only. They do not connect to
exchanges, networks, databases, or external services, and do not emit trading or
execution commands. The orchestrator runs only when called by local code or
tests; it is not a scheduler, daemon, server, or background job runner.
"""

from __future__ import annotations

from hunter.run_orchestrator.engine import build_research_run_result
from hunter.run_orchestrator.models import (
    EMPTY_RUN_ID,
    EMPTY_RUN_PLAN,
    FORBIDDEN_RUN_ORCHESTRATOR_TERMS,
    HUMAN_RESEARCH_ONLY,
    INVALID_OUTPUT_DIR,
    INVALID_RUN_CONFIG,
    INVALID_RUN_PLAN,
    INVALID_STEP_INPUTS,
    NETWORK_REFERENCE_DETECTED,
    NO_ACTION_COMMANDS_EMITTED,
    NO_DAEMON,
    NO_DATABASE,
    NO_EXCHANGE_CONNECTION,
    NO_FILE_INGESTION,
    NO_FREQTRADE_INPUT,
    NO_NETWORK_CONNECTION,
    NO_SCHEDULER,
    NO_WEB_UI,
    NOT_TRADING_ADVICE,
    OK,
    PATH_TRAVERSAL_DETECTED,
    RESEARCH_ONLY,
    RUN_BLOCKED,
    RUN_ORCHESTRATOR_ADVISORY_REASON_CODES,
    RUN_ORCHESTRATOR_BLOCKING_REASON_CODES,
    RUN_ORCHESTRATOR_REASON_CODES,
    RUN_ORCHESTRATOR_STEP_REASON_CODES,
    RUN_ORCHESTRATOR_VERSION,
    STEP_BLOCKED,
    STEP_FAILED,
    STEP_SKIPPED,
    UNSAFE_RUN_CONTENT,
    UNKNOWN_STEP_KIND,
    UNSUPPORTED_STEP_KIND,
    ResearchRunArtifact,
    ResearchRunConfig,
    ResearchRunDataQuality,
    ResearchRunPlan,
    ResearchRunResult,
    ResearchRunSafetyFlags,
    ResearchRunState,
    ResearchRunStep,
    ResearchRunStepKind,
    ResearchRunStepResult,
    ResearchRunStepState,
)
from hunter.run_orchestrator.writer import (
    DEFAULT_CSV_PATH,
    DEFAULT_JSON_PATH,
    DEFAULT_MD_PATH,
    atomic_write_csv_research_run_result,
    atomic_write_json_research_run_result,
    atomic_write_markdown_research_run_result,
    research_run_result_to_csv_text,
    research_run_result_to_dict,
    research_run_result_to_json_text,
    research_run_result_to_markdown_text,
    write_research_run_result,
)

__all__ = [
    "build_research_run_result",
    "research_run_result_to_dict",
    "research_run_result_to_json_text",
    "research_run_result_to_csv_text",
    "research_run_result_to_markdown_text",
    "write_research_run_result",
    "atomic_write_json_research_run_result",
    "atomic_write_csv_research_run_result",
    "atomic_write_markdown_research_run_result",
    "DEFAULT_JSON_PATH",
    "DEFAULT_CSV_PATH",
    "DEFAULT_MD_PATH",
    "RUN_ORCHESTRATOR_VERSION",
    "ResearchRunPlan",
    "ResearchRunStep",
    "ResearchRunStepKind",
    "ResearchRunStepState",
    "ResearchRunConfig",
    "ResearchRunStepResult",
    "ResearchRunResult",
    "ResearchRunArtifact",
    "ResearchRunDataQuality",
    "ResearchRunSafetyFlags",
    "ResearchRunState",
    "FORBIDDEN_RUN_ORCHESTRATOR_TERMS",
    "RUN_ORCHESTRATOR_REASON_CODES",
    "RUN_ORCHESTRATOR_BLOCKING_REASON_CODES",
    "RUN_ORCHESTRATOR_STEP_REASON_CODES",
    "RUN_ORCHESTRATOR_ADVISORY_REASON_CODES",
    "OK",
    "RUN_BLOCKED",
    "STEP_FAILED",
    "STEP_BLOCKED",
    "STEP_SKIPPED",
    "UNKNOWN_STEP_KIND",
    "UNSUPPORTED_STEP_KIND",
    "UNSAFE_RUN_CONTENT",
    "INVALID_RUN_PLAN",
    "INVALID_RUN_CONFIG",
    "INVALID_OUTPUT_DIR",
    "INVALID_STEP_INPUTS",
    "PATH_TRAVERSAL_DETECTED",
    "NETWORK_REFERENCE_DETECTED",
    "EMPTY_RUN_PLAN",
    "EMPTY_RUN_ID",
    "RESEARCH_ONLY",
    "NOT_TRADING_ADVICE",
    "NO_FILE_INGESTION",
    "NO_NETWORK_CONNECTION",
    "NO_EXCHANGE_CONNECTION",
    "NO_FREQTRADE_INPUT",
    "NO_SCHEDULER",
    "NO_DAEMON",
    "NO_WEB_UI",
    "NO_DATABASE",
    "NO_ACTION_COMMANDS_EMITTED",
    "HUMAN_RESEARCH_ONLY",
]
