"""Public API for the research campaign compiler and batch orchestrator (MVP-69/MVP-70 / SPEC-070).

No subprocess, threading, network, eval, exec, or dynamic code.
"""

from __future__ import annotations

from hunter.research_campaign.engine import (
    build_campaign_execution_manifest,
    build_dossier,
    build_evidence_summary,
    build_status_summary,
    compile_campaign_definition,
    run_campaign,
)
from hunter.research_campaign.errors import (
    ResearchCampaignCompilationError,
    ResearchCampaignDefinitionError,
    ResearchCampaignError,
    ResearchCampaignExecutionError,
    ResearchCampaignFilterError,
    ResearchCampaignRegistrationError,
    ResearchCampaignResumeError,
    ResearchCampaignRunnerError,
    ResearchCampaignSafetyError,
    ResearchCampaignWriterError,
)
from hunter.research_campaign.models import (
    RESEARCH_CAMPAIGN_REASON_CODES,
    RESEARCH_CAMPAIGN_VERSION,
    SPEC_VERSION,
    UNAVAILABLE,
    CampaignArtifactManifest,
    CampaignCheckpoint,
    CampaignDossier,
    CampaignEvidenceSummary,
    CampaignExecutionManifest,
    CampaignExecutionPolicy,
    CampaignFilterRule,
    CampaignOutputPolicy,
    CampaignParameterSet,
    CampaignRegistrationSet,
    CampaignResumeManifest,
    CampaignStatus,
    CampaignStatusSummary,
    CompiledCampaign,
    CompiledExperiment,
    ExperimentEvidence,
    ExperimentExecutionRecord,
    ExperimentOutcome,
    FamilyReference,
    FilterOperator,
    HistoricalDataReference,
    IndependenceMetadata,
    MetricFamilyScope,
    PriorExperimentEvidence,
    RegimePolicy,
    ResearchCampaignDefinition,
    ResearchCampaignSafetyFlags,
    ResumePolicy,
    StatisticalConfidenceConfigReference,
    StrategyReference,
    UniversePlanReference,
    WalkForwardTemplateReference,
)
from hunter.research_campaign.writer import CampaignWriter

__all__ = [
    # Version
    "RESEARCH_CAMPAIGN_VERSION",
    "SPEC_VERSION",
    "UNAVAILABLE",
    # Enums
    "FilterOperator",
    "CampaignExecutionPolicy",
    "ResumePolicy",
    "CampaignStatus",
    "ExperimentOutcome",
    # Errors
    "ResearchCampaignError",
    "ResearchCampaignDefinitionError",
    "ResearchCampaignCompilationError",
    "ResearchCampaignFilterError",
    "ResearchCampaignRegistrationError",
    "ResearchCampaignResumeError",
    "ResearchCampaignRunnerError",
    "ResearchCampaignWriterError",
    "ResearchCampaignSafetyError",
    "ResearchCampaignExecutionError",
    "RESEARCH_CAMPAIGN_REASON_CODES",
    # Models
    "ResearchCampaignSafetyFlags",
    "StrategyReference",
    "HistoricalDataReference",
    "UniversePlanReference",
    "WalkForwardTemplateReference",
    "StatisticalConfidenceConfigReference",
    "FamilyReference",
    "MetricFamilyScope",
    "RegimePolicy",
    "IndependenceMetadata",
    "CampaignFilterRule",
    "CampaignParameterSet",
    "CampaignOutputPolicy",
    "ResearchCampaignDefinition",
    "CompiledExperiment",
    "CompiledCampaign",
    "CampaignRegistrationSet",
    "CampaignExecutionManifest",
    "ExperimentEvidence",
    "ExperimentExecutionRecord",
    "CampaignCheckpoint",
    "PriorExperimentEvidence",
    "CampaignResumeManifest",
    "CampaignStatusSummary",
    "CampaignEvidenceSummary",
    "CampaignDossier",
    "CampaignArtifactManifest",
    # Writer
    "CampaignWriter",
    # Engine functions
    "compile_campaign_definition",
    "build_campaign_execution_manifest",
    "run_campaign",
    "build_dossier",
    "build_status_summary",
    "build_evidence_summary",
]
