"""MVP-42 — Local Research Human Review Decision Log Cross-Artifact Consistency."""

from __future__ import annotations

from hunter.human_review_decision_log_consistency.engine import (
    build_human_review_decision_log_consistency_report,
)
from hunter.human_review_decision_log_consistency.models import (
    FORBIDDEN_HUMAN_REVIEW_DECISION_LOG_CONSISTENCY_TERMS,
    HUMAN_REVIEW_DECISION_LOG_CONSISTENCY_VERSION,
    HumanReviewDecisionLogConsistencyConfig,
    HumanReviewDecisionLogConsistencyCrossReference,
    HumanReviewDecisionLogConsistencyDataQuality,
    HumanReviewDecisionLogConsistencyIssue,
    HumanReviewDecisionLogConsistencyIssueType,
    HumanReviewDecisionLogConsistencyLink,
    HumanReviewDecisionLogConsistencyLinkType,
    HumanReviewDecisionLogConsistencyInput,
    HumanReviewDecisionLogConsistencyReasonCode,
    HumanReviewDecisionLogConsistencyReport,
    HumanReviewDecisionLogConsistencySafetyFlags,
    HumanReviewDecisionLogConsistencySeverity,
    HumanReviewDecisionLogConsistencyState,
    INCONSISTENT_BLOCKED_STATUS,
    INCONSISTENT_MISSING_STATUS,
    INCONSISTENT_ORPHAN_STATUS,
    MISMATCHED_QUEUE_PRIORITY,
    MISMATCHED_QUEUE_REASON_CODES,
    MISMATCHED_QUEUE_SEVERITY,
    MISMATCHED_QUEUE_STATE,
    MISSING_DECISION_LOG_REF,
    NOT_APPLICABLE_RC,
    OK,
    ORPHAN_DECISION_LOG_REF,
    SAFETY_BLOCKED,
    SAFETY_NOTICE,
    UNSAFE_CONTENT,
    FORBIDDEN_TERM_PRESENT,
    INPUT_BLOCKED,
    CONSISTENCY_DEGRADED,
    has_unsafe_human_review_decision_log_consistency_content,
)

__all__ = [
    "build_human_review_decision_log_consistency_report",
    "FORBIDDEN_HUMAN_REVIEW_DECISION_LOG_CONSISTENCY_TERMS",
    "HUMAN_REVIEW_DECISION_LOG_CONSISTENCY_VERSION",
    "HumanReviewDecisionLogConsistencyConfig",
    "HumanReviewDecisionLogConsistencyCrossReference",
    "HumanReviewDecisionLogConsistencyDataQuality",
    "HumanReviewDecisionLogConsistencyIssue",
    "HumanReviewDecisionLogConsistencyIssueType",
    "HumanReviewDecisionLogConsistencyLink",
    "HumanReviewDecisionLogConsistencyLinkType",
    "HumanReviewDecisionLogConsistencyInput",
    "HumanReviewDecisionLogConsistencyReasonCode",
    "HumanReviewDecisionLogConsistencyReport",
    "HumanReviewDecisionLogConsistencySafetyFlags",
    "HumanReviewDecisionLogConsistencySeverity",
    "HumanReviewDecisionLogConsistencyState",
    "INCONSISTENT_BLOCKED_STATUS",
    "INCONSISTENT_MISSING_STATUS",
    "INCONSISTENT_ORPHAN_STATUS",
    "MISMATCHED_QUEUE_PRIORITY",
    "MISMATCHED_QUEUE_REASON_CODES",
    "MISMATCHED_QUEUE_SEVERITY",
    "MISMATCHED_QUEUE_STATE",
    "MISSING_DECISION_LOG_REF",
    "NOT_APPLICABLE_RC",
    "OK",
    "ORPHAN_DECISION_LOG_REF",
    "SAFETY_BLOCKED",
    "SAFETY_NOTICE",
    "UNSAFE_CONTENT",
    "FORBIDDEN_TERM_PRESENT",
    "INPUT_BLOCKED",
    "CONSISTENCY_DEGRADED",
    "has_unsafe_human_review_decision_log_consistency_content",
]
