"""Writer for the Strategy Contract Consumption Adapter (MVP-57)."""

from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path
from typing import Any, Mapping

from hunter.strategy_contract_consumer.models import (
    StrategyContractConsumerConfig,
    ValidatedStrategyContext,
)


_SAFETY_NOTICE = (
    "This output is a human-audit / research-only artifact generated by the "
    "Strategy Contract Consumption Adapter. It is not a trading signal, strategy "
    "recommendation, or execution instruction. Any use beyond research requires "
    "explicit human review and authorization."
)


def _mapping_to_dict(value: Mapping[str, Any] | dict[str, Any]) -> dict[str, Any]:
    """Recursively convert a mapping to a plain, JSON-safe dict."""
    result: dict[str, Any] = {}
    for key, val in value.items():
        str_key = str(key)
        if isinstance(val, Mapping):
            result[str_key] = _mapping_to_dict(val)
        elif isinstance(val, (list, tuple)):
            result[str_key] = [_mapping_to_dict(item) if isinstance(item, Mapping) else item for item in val]
        else:
            result[str_key] = val
    return result


def strategy_context_result_to_dict(
    result: ValidatedStrategyContext,
) -> dict[str, Any]:
    """Serialize a validation result to an ordered, deterministic dictionary."""
    return {
        "kind": "strategy_contract_validation",
        "version": result.version,
        "safety_notice": _SAFETY_NOTICE,
        "accepted": result.accepted,
        "source_fingerprint": result.source_fingerprint,
        "source_path": result.source_path,
        "input_version": result.input_version,
        "mode": result.mode,
        "research_only": result.research_only,
        "human_approval_required": result.human_approval_required,
        "whitelist": list(result.whitelist),
        "blacklist": list(result.blacklist),
        "safety_flags": dict(sorted(result.safety_flags.items())),
        "reason_codes": list(result.reason_codes),
        "metadata": _mapping_to_dict(result.metadata),
        "validated_at": result.validated_at.isoformat(),
        "generated_at": result.generated_at.isoformat() if result.generated_at is not None else None,
    }


def strategy_context_result_to_json_text(
    result: ValidatedStrategyContext,
    *,
    indent: int | None = 2,
) -> str:
    """Serialize a validation result to JSON text."""
    payload = strategy_context_result_to_dict(result)
    text = json.dumps(
        payload,
        indent=indent,
        sort_keys=True,
        ensure_ascii=False,
    )
    return text + "\n"


def strategy_context_result_to_markdown_text(
    result: ValidatedStrategyContext,
    *,
    json_path: Path | str | None = None,
    markdown_path: Path | str | None = None,
) -> str:
    """Serialize a validation result to Markdown text."""
    lines: list[str] = []
    lines.append("# Strategy Contract Validation")
    lines.append("")
    lines.append(f"**Safety Notice:** {_SAFETY_NOTICE}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **Accepted:** {result.accepted}")
    lines.append(f"- **Mode:** {result.mode}")
    lines.append(f"- **Whitelist Count:** {len(result.whitelist)}")
    lines.append(f"- **Blacklist Count:** {len(result.blacklist)}")
    lines.append(f"- **Research Only:** {result.research_only}")
    lines.append(f"- **Human Approval Required:** {result.human_approval_required}")
    lines.append("")
    lines.append("## Whitelist")
    lines.append("")
    if result.whitelist:
        for pair in result.whitelist:
            lines.append(f"- {pair}")
    else:
        lines.append("_None_")
    lines.append("")
    lines.append("## Blacklist")
    lines.append("")
    if result.blacklist:
        for pair in result.blacklist:
            lines.append(f"- {pair}")
    else:
        lines.append("_None_")
    lines.append("")
    lines.append("## Safety Flags")
    lines.append("")
    lines.append("| Flag | Value |")
    lines.append("|------|-------|")
    for key, value in sorted(result.safety_flags.items()):
        lines.append(f"| {key} | {value} |")
    lines.append("")
    lines.append("## Reason Codes")
    lines.append("")
    for code in result.reason_codes:
        lines.append(f"- {code}")
    lines.append("")
    lines.append("## Metadata")
    lines.append("")
    if result.metadata:
        lines.append("```json")
        lines.append(json.dumps(_mapping_to_dict(result.metadata), sort_keys=True, indent=2))
        lines.append("```")
    else:
        lines.append("_None_")
    lines.append("")
    lines.append("## Audit")
    lines.append("")
    lines.append(f"- **Adapter Version:** {result.version}")
    lines.append(f"- **Input Version:** {result.input_version}")
    lines.append(f"- **Generated At:** {result.generated_at.isoformat() if result.generated_at is not None else '_None_'}")
    lines.append(f"- **Validated At:** {result.validated_at.isoformat()}")
    lines.append(f"- **Source Fingerprint:** {result.source_fingerprint}")
    lines.append(f"- **Source Path:** {result.source_path}")
    if json_path is not None or markdown_path is not None:
        lines.append("")
        lines.append("## Artifacts")
        lines.append("")
        if json_path is not None:
            lines.append(f"- **JSON:** {json_path}")
        if markdown_path is not None:
            lines.append(f"- **Markdown:** {markdown_path}")
    lines.append("")
    return "\n".join(lines)


def _atomic_write_text(path: Path, text: str) -> None:
    """Write text to a file atomically using a temp file and os.replace."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    # Use a temp file in the same directory so os.replace is atomic on the same filesystem.
    fd, tmp_path = tempfile.mkstemp(
        dir=path.parent,
        prefix=f".{path.name}",
        suffix=".tmp",
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.replace(tmp_path, path)
    finally:
        try:
            if Path(tmp_path).exists():
                Path(tmp_path).unlink()
        except OSError:
            pass


def write_strategy_context_validation_result(
    result: ValidatedStrategyContext,
    output_dir: Path | str,
    config: StrategyContractConsumerConfig,
) -> tuple[Path, Path]:
    """Write JSON and Markdown artifacts atomically.

    Returns the paths to the written JSON and Markdown files.
    """
    json_path = Path(output_dir) / config.json_filename
    markdown_path = Path(config.markdown_output_dir) / config.markdown_filename

    json_text = strategy_context_result_to_json_text(result)
    markdown_text = strategy_context_result_to_markdown_text(
        result,
        json_path=json_path,
        markdown_path=markdown_path,
    )

    _atomic_write_text(json_path, json_text)
    _atomic_write_text(markdown_path, markdown_text)

    return json_path, markdown_path
