"""Public API exports for hunter.review_index package."""

from .models import (
    DEFAULT_BLOCKED,
    EMPTY_INDEX,
    FORBIDDEN_INDEX_TERMS,
    INDEX_ERROR,
    INVALID_REPORT,
    INVALID_REVIEW,
    MISSING_REPORTS,
    MISSING_REVIEWS,
    REASON_CODES,
    UNSAFE_INDEX_CONTENT,
    UNSAFE_REPORT_STATE,
    UNSAFE_REVIEW_STATE,
    UNSAFE_SAFETY_FLAGS,
    UNSUPPORTED_REPORT_VERSION,
    UNSUPPORTED_REVIEW_VERSION,
    IndexConfig,
    IndexDataQuality,
    IndexEntry,
    IndexEntryKind,
    IndexOutputFormat,
    IndexSafetyFlags,
    IndexState,
    IndexSummary,
    ReviewIndex,
)
from .engine import (
    build_index_data_quality,
    build_index_entry,
    build_index_safety_flags,
    build_index_summary,
    build_review_index,
    has_unsafe_index_content,
)

from .writer import (
    DEFAULT_REVIEW_INDEX_JSON_PATH,
    DEFAULT_REVIEW_INDEX_MARKDOWN_PATH,
    atomic_write_json_review_index,
    atomic_write_markdown_review_index,
    index_data_quality_to_dict,
    index_entry_to_dict,
    index_safety_flags_to_dict,
    index_summary_to_dict,
    review_index_to_dict,
    review_index_to_markdown,
    write_review_index,
)

__all__ = [
    # Enums
    "IndexState",
    "IndexEntryKind",
    "IndexOutputFormat",
    # Models
    "IndexConfig",
    "IndexSafetyFlags",
    "IndexEntry",
    "IndexSummary",
    "IndexDataQuality",
    "ReviewIndex",
    # Reason codes
    "MISSING_REPORTS",
    "MISSING_REVIEWS",
    "INVALID_REPORT",
    "INVALID_REVIEW",
    "UNSUPPORTED_REPORT_VERSION",
    "UNSUPPORTED_REVIEW_VERSION",
    "UNSAFE_REPORT_STATE",
    "UNSAFE_REVIEW_STATE",
    "UNSAFE_SAFETY_FLAGS",
    "UNSAFE_INDEX_CONTENT",
    "EMPTY_INDEX",
    "INDEX_ERROR",
    "DEFAULT_BLOCKED",
    "REASON_CODES",
    "FORBIDDEN_INDEX_TERMS",
    # Engine functions
    "has_unsafe_index_content",
    "build_index_safety_flags",
    "build_index_entry",
    "build_index_summary",
    "build_index_data_quality",
    "build_review_index",
    # Writer constants
    "DEFAULT_REVIEW_INDEX_JSON_PATH",
    "DEFAULT_REVIEW_INDEX_MARKDOWN_PATH",
    # Writer functions
    "index_entry_to_dict",
    "index_summary_to_dict",
    "index_data_quality_to_dict",
    "index_safety_flags_to_dict",
    "review_index_to_dict",
    "review_index_to_markdown",
    "atomic_write_json_review_index",
    "atomic_write_markdown_review_index",
    "write_review_index",
]
