from __future__ import annotations

from hunter.discovery.engine import (
    build_discovery_report,
    build_discovery_safety_flags,
    build_discovery_score,
    build_discovery_universe_summary,
    calculate_alignment_score,
    calculate_data_quality_score,
    classify_discovery_candidate,
    has_unsafe_discovery_content,
    normalized_score,
)
from hunter.discovery.models import (
    ALIGNED_CONTEXT,
    DISCOVERY_ADVISORY_REASON_CODES,
    DISCOVERY_BLOCKING_REASON_CODES,
    DISCOVERY_FILTER_REASON_CODES,
    DISCOVERY_INSUFFICIENT_DATA_REASON_CODES,
    DISCOVERY_REASON_CODES,
    DISCOVERY_VERSION,
    FORBIDDEN_DISCOVERY_TERMS,
    HUMAN_RESEARCH_ONLY,
    INVALID_DISCOVERY_SCORE,
    INVALID_PAIR,
    LOW_OPEN_INTEREST_SCORE,
    LOW_RELATIVE_STRENGTH_SCORE,
    MISALIGNED_CONTEXT,
    MISSING_OPEN_INTEREST_CONTEXT,
    MISSING_RELATIVE_STRENGTH_CONTEXT,
    MIXED_ALIGNMENT,
    NO_ACTION_COMMANDS_EMITTED,
    NO_FILE_READ_IN_ENGINE,
    NO_NETWORK_CONNECTION,
    OPEN_INTEREST_BLOCKED,
    OPEN_INTEREST_INSUFFICIENT_DATA,
    PASSED_DISCOVERY_FILTERS,
    RELATIVE_STRENGTH_BLOCKED,
    RELATIVE_STRENGTH_INSUFFICIENT_DATA,
    UNSAFE_DISCOVERY_CONTENT,
    DiscoveryCandidate,
    DiscoveryClassification,
    DiscoveryConfig,
    DiscoveryDataQuality,
    DiscoveryInput,
    DiscoveryInputKind,
    DiscoveryOpenInterestSummary,
    DiscoveryRelativeStrengthSummary,
    DiscoveryReport,
    DiscoverySafetyFlags,
    DiscoveryScore,
    DiscoveryState,
    DiscoveryUniverseSummary,
)

__all__ = [
    # Version
    "DISCOVERY_VERSION",
    # Enums
    "DiscoveryState",
    "DiscoveryClassification",
    "DiscoveryInputKind",
    # Reason code partitions
    "DISCOVERY_BLOCKING_REASON_CODES",
    "DISCOVERY_INSUFFICIENT_DATA_REASON_CODES",
    "DISCOVERY_FILTER_REASON_CODES",
    "DISCOVERY_ADVISORY_REASON_CODES",
    "DISCOVERY_REASON_CODES",
    # Individual reason codes
    "INVALID_PAIR",
    "INVALID_DISCOVERY_SCORE",
    "UNSAFE_DISCOVERY_CONTENT",
    "RELATIVE_STRENGTH_BLOCKED",
    "OPEN_INTEREST_BLOCKED",
    "MISSING_RELATIVE_STRENGTH_CONTEXT",
    "MISSING_OPEN_INTEREST_CONTEXT",
    "RELATIVE_STRENGTH_INSUFFICIENT_DATA",
    "OPEN_INTEREST_INSUFFICIENT_DATA",
    "LOW_RELATIVE_STRENGTH_SCORE",
    "LOW_OPEN_INTEREST_SCORE",
    "MISALIGNED_CONTEXT",
    "PASSED_DISCOVERY_FILTERS",
    "HUMAN_RESEARCH_ONLY",
    "NO_NETWORK_CONNECTION",
    "NO_FILE_READ_IN_ENGINE",
    "NO_ACTION_COMMANDS_EMITTED",
    "ALIGNED_CONTEXT",
    "MIXED_ALIGNMENT",
    # Forbidden terms
    "FORBIDDEN_DISCOVERY_TERMS",
    # Dataclasses
    "DiscoveryConfig",
    "DiscoverySafetyFlags",
    "DiscoveryRelativeStrengthSummary",
    "DiscoveryOpenInterestSummary",
    "DiscoveryInput",
    "DiscoveryScore",
    "DiscoveryUniverseSummary",
    "DiscoveryDataQuality",
    "DiscoveryCandidate",
    "DiscoveryReport",
    # Engine functions
    "build_discovery_safety_flags",
    "has_unsafe_discovery_content",
    "normalized_score",
    "calculate_alignment_score",
    "calculate_data_quality_score",
    "classify_discovery_candidate",
    "build_discovery_score",
    "build_discovery_universe_summary",
    "build_discovery_report",
]
