"""Public API for hunter.audit_scorecard package.

MVP-35 — Local Research Audit Readiness Scorecard.

All exports are deterministic, local, and audit-only. They do not connect to
exchanges, networks, databases, or external services, and do not emit trading or
execution commands. The scorecard runs only when called by local code or tests;
it is not a scheduler, daemon, server, or background job runner.
"""

from __future__ import annotations

from hunter.audit_scorecard.engine import (
    build_audit_scorecard_report,
    has_unsafe_audit_scorecard_content,
)
from hunter.audit_scorecard.models import (
    AUDIT_SCORECARD_ADVISORY_REASON_CODES,
    AUDIT_SCORECARD_BLOCKING_REASON_CODES,
    AUDIT_SCORECARD_REASON_CODES,
    CONFLICTING_FINDING,
    CONFLICTING_LINK,
    CONSISTENCY_DEGRADED,
    DUPLICATE_DIMENSION_ID,
    DUPLICATE_EVIDENCE_ID,
    DUPLICATE_FINDING_ID,
    DUPLICATE_LINK_ID,
    FORBIDDEN_AUDIT_SCORECARD_TERMS,
    FORBIDDEN_TERM_PRESENT,
    HUMAN_RESEARCH_ONLY,
    MISSING_MANUAL_REVIEW,
    MISSING_REQUIRED_DIMENSION,
    MISSING_SUPPORTING_EVIDENCE,
    NO_ACTION_COMMANDS_EMITTED,
    NO_DAEMON,
    NO_DATABASE,
    NO_EXCHANGE_CONNECTION,
    NO_FILE_INGESTION,
    NO_FREQTRADE_INPUT,
    NO_NETWORK_CONNECTION,
    NO_PRODUCTION_READINESS,
    NO_SCHEDULER,
    NO_WEB_UI,
    NOT_APPLICABLE_RC,
    NOT_TRADING_ADVICE,
    OK,
    ORPHAN_EVIDENCE,
    ORPHAN_LINK,
    SAFETY_BLOCKED,
    STALE_EVIDENCE,
    UNKNOWN_UPSTREAM_STATE,
    UNSAFE_CONTENT,
    UPSTREAM_BLOCKED,
    UPSTREAM_DEGRADED,
    AuditScorecardConfig,
    AuditScorecardDataQuality,
    AuditScorecardDimension,
    AuditScorecardDimensionResult,
    AuditScorecardDimensionState,
    AuditScorecardEvidenceRef,
    AuditScorecardFinding,
    AuditScorecardInput,
    AuditScorecardLink,
    AuditScorecardLinkType,
    AuditScorecardReasonCode,
    AuditScorecardReport,
    AuditScorecardSafetyFlags,
    AuditScorecardSeverity,
    AuditScorecardState,
)

__all__ = [
    "AUDIT_SCORECARD_ADVISORY_REASON_CODES",
    "AUDIT_SCORECARD_BLOCKING_REASON_CODES",
    "AUDIT_SCORECARD_REASON_CODES",
    "CONFLICTING_FINDING",
    "CONFLICTING_LINK",
    "CONSISTENCY_DEGRADED",
    "DUPLICATE_DIMENSION_ID",
    "DUPLICATE_EVIDENCE_ID",
    "DUPLICATE_FINDING_ID",
    "DUPLICATE_LINK_ID",
    "FORBIDDEN_AUDIT_SCORECARD_TERMS",
    "FORBIDDEN_TERM_PRESENT",
    "HUMAN_RESEARCH_ONLY",
    "MISSING_MANUAL_REVIEW",
    "MISSING_REQUIRED_DIMENSION",
    "MISSING_SUPPORTING_EVIDENCE",
    "NO_ACTION_COMMANDS_EMITTED",
    "NO_DAEMON",
    "NO_DATABASE",
    "NO_EXCHANGE_CONNECTION",
    "NO_FILE_INGESTION",
    "NO_FREQTRADE_INPUT",
    "NO_NETWORK_CONNECTION",
    "NO_PRODUCTION_READINESS",
    "NO_SCHEDULER",
    "NO_WEB_UI",
    "NOT_APPLICABLE_RC",
    "NOT_TRADING_ADVICE",
    "OK",
    "ORPHAN_EVIDENCE",
    "ORPHAN_LINK",
    "SAFETY_BLOCKED",
    "STALE_EVIDENCE",
    "UNKNOWN_UPSTREAM_STATE",
    "UNSAFE_CONTENT",
    "UPSTREAM_BLOCKED",
    "UPSTREAM_DEGRADED",
    "AuditScorecardConfig",
    "AuditScorecardDataQuality",
    "AuditScorecardDimension",
    "AuditScorecardDimensionResult",
    "AuditScorecardDimensionState",
    "AuditScorecardEvidenceRef",
    "AuditScorecardFinding",
    "AuditScorecardInput",
    "AuditScorecardLink",
    "AuditScorecardLinkType",
    "AuditScorecardReasonCode",
    "AuditScorecardReport",
    "AuditScorecardSafetyFlags",
    "AuditScorecardSeverity",
    "AuditScorecardState",
    "build_audit_scorecard_report",
    "has_unsafe_audit_scorecard_content",
]
