"""Public API for the hunter.backtest package.

MVP-28 — Local Research Backtesting Engine.

All functions and types exported here are deterministic, local, and research-only.
The engine does not connect to exchanges, networks, databases, or file systems,
and does not emit trading/execution/action commands.
"""

from __future__ import annotations

from hunter.backtest.engine import (
    build_backtest_report,
    build_backtest_safety_flags,
)
from hunter.backtest.models import (
    BACKTEST_ADVISORY_REASON_CODES,
    BACKTEST_BLOCKING_REASON_CODES,
    BACKTEST_FILTER_REASON_CODES,
    BACKTEST_INSUFFICIENT_DATA_REASON_CODES,
    BACKTEST_REASON_CODES,
    BACKTEST_VERSION,
    BacktestAllocationMode,
    BacktestCandidateDecision,
    BacktestCandidateResult,
    BacktestDataQuality,
    BacktestInput,
    BacktestInputKind,
    BacktestPortfolioResult,
    BacktestPortfolioSnapshot,
    BacktestPriceBar,
    BacktestReport,
    BacktestRunConfig,
    BacktestSafetyFlags,
    BacktestState,
    DISCOVERY_BLOCKED,
    EXCLUDED_BY_RESEARCH_CONSTRAINTS,
    FORBIDDEN_BACKTEST_TERMS,
    HUMAN_RESEARCH_ONLY,
    INSUFFICIENT_PRICE_HISTORY,
    INVALID_DATE,
    INVALID_PAIR,
    INVALID_PRICE,
    MIN_OBSERVATION_COUNT_NOT_MET,
    MISSING_DECISION_CONTEXT,
    MISSING_PRICE_HISTORY,
    NO_ACTION_COMMANDS_EMITTED,
    NO_FILE_READ_IN_ENGINE,
    NO_NETWORK_CONNECTION,
    NOT_EXECUTION_READY,
    NOT_TRADING_ADVICE,
    UNSAFE_BACKTEST_CONTENT,
    WATCHLIST_ZERO_WEIGHT,
    has_unsafe_backtest_content,
)
from hunter.backtest.writer import (
    atomic_write_csv_backtest_report,
    atomic_write_json_backtest_report,
    atomic_write_markdown_backtest_report,
    backtest_report_to_csv_text,
    backtest_report_to_dict,
    backtest_report_to_json_text,
    backtest_report_to_markdown,
    write_backtest_report,
)

__all__ = [
    "BACKTEST_ADVISORY_REASON_CODES",
    "BACKTEST_BLOCKING_REASON_CODES",
    "BACKTEST_FILTER_REASON_CODES",
    "BACKTEST_INSUFFICIENT_DATA_REASON_CODES",
    "BACKTEST_REASON_CODES",
    "BACKTEST_VERSION",
    "BacktestAllocationMode",
    "BacktestCandidateDecision",
    "BacktestCandidateResult",
    "BacktestDataQuality",
    "BacktestInput",
    "BacktestInputKind",
    "BacktestPortfolioResult",
    "BacktestPortfolioSnapshot",
    "BacktestPriceBar",
    "BacktestReport",
    "BacktestRunConfig",
    "BacktestSafetyFlags",
    "BacktestState",
    "DISCOVERY_BLOCKED",
    "EXCLUDED_BY_RESEARCH_CONSTRAINTS",
    "FORBIDDEN_BACKTEST_TERMS",
    "HUMAN_RESEARCH_ONLY",
    "INSUFFICIENT_PRICE_HISTORY",
    "INVALID_DATE",
    "INVALID_PAIR",
    "INVALID_PRICE",
    "MIN_OBSERVATION_COUNT_NOT_MET",
    "MISSING_DECISION_CONTEXT",
    "MISSING_PRICE_HISTORY",
    "NO_ACTION_COMMANDS_EMITTED",
    "NO_FILE_READ_IN_ENGINE",
    "NO_NETWORK_CONNECTION",
    "NOT_EXECUTION_READY",
    "NOT_TRADING_ADVICE",
    "UNSAFE_BACKTEST_CONTENT",
    "WATCHLIST_ZERO_WEIGHT",
    "atomic_write_csv_backtest_report",
    "atomic_write_json_backtest_report",
    "atomic_write_markdown_backtest_report",
    "backtest_report_to_csv_text",
    "backtest_report_to_dict",
    "backtest_report_to_json_text",
    "backtest_report_to_markdown",
    "build_backtest_report",
    "build_backtest_safety_flags",
    "has_unsafe_backtest_content",
    "write_backtest_report",
]
