"""Public API for the research backtest comparison harness (MVP-65 / SPEC-066)."""

from __future__ import annotations

from hunter.research_backtest_comparison.compatibility_harness import (
    run_freqtrade_compatibility_smoke_test,
)
from hunter.research_backtest_comparison.compatibility_writer import (
    FreqtradeCompatibilityWriter,
    write_all_compatibility_artifacts,
)
from hunter.research_backtest_comparison.comparison import (
    compare_backtest_metrics,
    compare_backtest_results,
)
from hunter.research_backtest_comparison.engine import (
    build_backtest_comparison_report,
    run_research_backtest_comparison,
)
from hunter.research_backtest_comparison.errors import (
    ResearchBacktestComparisonConfigError,
    ResearchBacktestComparisonError,
    ResearchBacktestComparisonExecutableError,
    ResearchBacktestComparisonFairnessError,
    ResearchBacktestComparisonParserError,
    ResearchBacktestComparisonRunnerError,
    ResearchBacktestComparisonValidationError,
    ResearchBacktestComparisonWriterError,
)
from hunter.research_backtest_comparison.fingerprint import (
    command_fingerprint,
    comparison_fingerprint_from_result,
    config_fingerprint,
    data_fingerprint,
    fairness_fingerprint,
    metrics_fingerprint,
    pairlist_fingerprint,
    raw_result_fingerprint,
    report_fingerprint,
    run_result_fingerprint,
    safety_flags_fingerprint,
    strategy_fingerprint,
)
from hunter.research_backtest_comparison.models import (
    RESEARCH_BACKTEST_COMPARISON_VERSION,
    SPEC_VERSION,
    UNAVAILABLE,
    BacktestArmInput,
    BacktestArmLabel,
    BacktestComparisonConfig,
    BacktestComparisonManifest,
    BacktestComparisonReport,
    BacktestComparisonResult,
    BacktestFairnessManifest,
    BacktestMetrics,
    BacktestRunResult,
    CompatibilityStatus,
    EvidenceAvailability,
    FreqtradeCompatibilityInput,
    FreqtradeCompatibilityManifest,
    FreqtradeCompatibilityReport,
    FreqtradeCompatibilityResult,
    FreqtradeExecutableInfo,
    MetricInterpretation,
    ResearchBacktestSafetyFlags,
    RESEARCH_BACKTEST_COMPARISON_REASON_CODES,
    classify_evidence_availability,
)
from hunter.research_backtest_comparison.writer import (
    BacktestComparisonWriter,
    write_all_backtest_comparison_artifacts,
    write_backtest_comparison_report,
)

__all__ = [
    "RESEARCH_BACKTEST_COMPARISON_VERSION",
    "SPEC_VERSION",
    "UNAVAILABLE",
    "BacktestArmInput",
    "BacktestArmLabel",
    "BacktestComparisonConfig",
    "BacktestComparisonManifest",
    "BacktestComparisonReport",
    "BacktestComparisonResult",
    "BacktestComparisonWriter",
    "ResearchBacktestComparisonWriterError",
    "BacktestFairnessManifest",
    "BacktestMetrics",
    "BacktestRunResult",
    "CompatibilityStatus",
    "EvidenceAvailability",
    "FreqtradeCompatibilityInput",
    "FreqtradeCompatibilityManifest",
    "FreqtradeCompatibilityReport",
    "FreqtradeCompatibilityResult",
    "FreqtradeExecutableInfo",
    "MetricInterpretation",
    "ResearchBacktestSafetyFlags",
    "ResearchBacktestComparisonError",
    "ResearchBacktestComparisonConfigError",
    "ResearchBacktestComparisonExecutableError",
    "ResearchBacktestComparisonFairnessError",
    "ResearchBacktestComparisonParserError",
    "ResearchBacktestComparisonRunnerError",
    "ResearchBacktestComparisonValidationError",
    "RESEARCH_BACKTEST_COMPARISON_REASON_CODES",
    "run_freqtrade_compatibility_smoke_test",
    "FreqtradeCompatibilityWriter",
    "write_all_compatibility_artifacts",
    "classify_evidence_availability",
    "build_backtest_comparison_report",
    "command_fingerprint",
    "compare_backtest_metrics",
    "compare_backtest_results",
    "comparison_fingerprint_from_result",
    "config_fingerprint",
    "data_fingerprint",
    "fairness_fingerprint",
    "metrics_fingerprint",
    "pairlist_fingerprint",
    "raw_result_fingerprint",
    "report_fingerprint",
    "run_research_backtest_comparison",
    "run_result_fingerprint",
    "safety_flags_fingerprint",
    "strategy_fingerprint",
    "write_all_backtest_comparison_artifacts",
    "write_backtest_comparison_report",
]
