"""hunter.research_market_data package — MVP-63 / SPEC-064.

Read-only CSV candle ingestion, validation, benchmark alignment, and
adapter layer for the existing Relative Strength and Discovery research engines.
"""

from __future__ import annotations

from hunter.research_market_data.adapters import (
    build_discovery_input_bundle,
    build_relative_strength_run_inputs,
    candle_series_to_ohlcv_rows,
    discovery_summaries_to_inputs,
    relative_strength_report_to_discovery_summaries,
)
from hunter.research_market_data.aligner import (
    align_benchmark,
    align_candidate,
    build_candle_series,
)
from hunter.research_market_data.csv_loader import load_csv_file
from hunter.research_market_data.engine import build_research_market_data_bundle
from hunter.research_market_data.errors import (
    ResearchMarketDataBundleError,
    ResearchMarketDataConfigError,
    ResearchMarketDataError,
    ResearchMarketDataIOError,
    ResearchMarketDataValidationError,
    ResearchMarketDataWriterError,
)
from hunter.research_market_data.fingerprint import (
    bundle_fingerprint,
    policy_fingerprint,
    series_fingerprint,
)
from hunter.research_market_data.models import (
    AMBIGUOUS_COLUMN,
    ALL_CANDIDATES_EXCLUDED,
    BELOW_MIN_ROWS,
    BTC_BENCHMARK_MISSING,
    BTC_ONLY_MODE,
    CandleSeries,
    DiscoveryInputBundle,
    DUPLICATE_TIMESTAMP,
    ETH_BENCHMARK_MISSING,
    EMPTY_FILE,
    ExcludedMarketDataInput,
    FORBIDDEN_PATH,
    GAPS_FOUND,
    HUMAN_RESEARCH_ONLY,
    INPUTS_ALREADY_LOADED,
    INSUFFICIENT_COVERAGE,
    INVALID_CONFIG,
    INVALID_CSV_HEADER,
    INVALID_FILE_PATH,
    INVALID_NUMERIC,
    INVALID_OHLC_RELATION,
    INVALID_SAFETY_FLAGS,
    LEVERAGED_TOKEN_EXCLUDED,
    MarketDataFileSpec,
    MarketDataSafetyFlags,
    MarketDataSourceRef,
    MissingInterval,
    MISSING_COLUMN,
    MISSING_FILE,
    NO_ACTION_COMMANDS_EMITTED,
    NO_DATABASE_CONNECTION,
    NO_FILE_READ_IN_ENGINE,
    NO_NETWORK_CONNECTION,
    NAIVE_TIMESTAMP,
    NON_FINITE_VALUE,
    NON_UTC_TIMESTAMP,
    NEGATIVE_OR_ZERO_PRICE,
    NEGATIVE_VOLUME,
    NormalizedCandle,
    OUT_OF_ORDER_INPUT,
    RawCandleRow,
    RESEARCH_MARKET_DATA_REASON_CODES,
    RESEARCH_MARKET_DATA_VERSION,
    ResearchMarketDataBundle,
    ResearchMarketDataConfig,
    ResearchMarketDataManifest,
    RelativeStrengthRunInputs,
    SPEC_VERSION,
    STABLECOIN_PAIR_EXCLUDED,
    SYMBOL_NORMALIZATION_FAILED,
    TIMESTAMP_PARSE_ERROR,
    UNSUPPORTED_QUOTE_CURRENCY,
    UNSUPPORTED_TIMEFRAME,
    UNSAFE_SYMBOL_CONTENT,
)
from hunter.research_market_data.symbol_normalizer import normalize_symbol
from hunter.research_market_data.validator import build_normalized_candles, detect_timeframe
from hunter.research_market_data.writer import (
    ResearchMarketDataBundleWriterError,
    atomic_write_json_research_market_data_bundle,
    atomic_write_markdown_research_market_data_bundle,
    research_market_data_bundle_to_dict,
    research_market_data_bundle_to_json_text,
    research_market_data_bundle_to_markdown_text,
    write_research_market_data_bundle,
)

__version__ = RESEARCH_MARKET_DATA_VERSION

__all__ = [
    # Errors
    "ResearchMarketDataError",
    "ResearchMarketDataConfigError",
    "ResearchMarketDataIOError",
    "ResearchMarketDataValidationError",
    "ResearchMarketDataBundleError",
    "ResearchMarketDataWriterError",
    "ResearchMarketDataBundleWriterError",
    # Version
    "RESEARCH_MARKET_DATA_VERSION",
    "SPEC_VERSION",
    "RESEARCH_MARKET_DATA_REASON_CODES",
    # Models
    "MarketDataSafetyFlags",
    "ResearchMarketDataConfig",
    "MarketDataFileSpec",
    "MarketDataSourceRef",
    "RawCandleRow",
    "NormalizedCandle",
    "MissingInterval",
    "CandleSeries",
    "ExcludedMarketDataInput",
    "ResearchMarketDataManifest",
    "ResearchMarketDataBundle",
    "RelativeStrengthRunInputs",
    "DiscoveryInputBundle",
    # Reason codes
    "AMBIGUOUS_COLUMN",
    "ALL_CANDIDATES_EXCLUDED",
    "BELOW_MIN_ROWS",
    "BTC_BENCHMARK_MISSING",
    "BTC_ONLY_MODE",
    "DUPLICATE_TIMESTAMP",
    "ETH_BENCHMARK_MISSING",
    "EMPTY_FILE",
    "FORBIDDEN_PATH",
    "GAPS_FOUND",
    "HUMAN_RESEARCH_ONLY",
    "INPUTS_ALREADY_LOADED",
    "INSUFFICIENT_COVERAGE",
    "INVALID_CONFIG",
    "INVALID_CSV_HEADER",
    "INVALID_FILE_PATH",
    "INVALID_NUMERIC",
    "INVALID_OHLC_RELATION",
    "INVALID_SAFETY_FLAGS",
    "LEVERAGED_TOKEN_EXCLUDED",
    "MISSING_COLUMN",
    "MISSING_FILE",
    "NAIVE_TIMESTAMP",
    "NON_FINITE_VALUE",
    "NON_UTC_TIMESTAMP",
    "NEGATIVE_OR_ZERO_PRICE",
    "NEGATIVE_VOLUME",
    "NO_ACTION_COMMANDS_EMITTED",
    "NO_DATABASE_CONNECTION",
    "NO_FILE_READ_IN_ENGINE",
    "NO_NETWORK_CONNECTION",
    "OUT_OF_ORDER_INPUT",
    "STABLECOIN_PAIR_EXCLUDED",
    "SYMBOL_NORMALIZATION_FAILED",
    "TIMESTAMP_PARSE_ERROR",
    "UNSUPPORTED_QUOTE_CURRENCY",
    "UNSUPPORTED_TIMEFRAME",
    "UNSAFE_SYMBOL_CONTENT",
    # Functions
    "normalize_symbol",
    "load_csv_file",
    "build_normalized_candles",
    "detect_timeframe",
    "build_candle_series",
    "align_candidate",
    "align_benchmark",
    "series_fingerprint",
    "policy_fingerprint",
    "bundle_fingerprint",
    "build_research_market_data_bundle",
    "candle_series_to_ohlcv_rows",
    "build_relative_strength_run_inputs",
    "relative_strength_report_to_discovery_summaries",
    "discovery_summaries_to_inputs",
    "build_discovery_input_bundle",
    "research_market_data_bundle_to_dict",
    "research_market_data_bundle_to_json_text",
    "research_market_data_bundle_to_markdown_text",
    "write_research_market_data_bundle",
    "atomic_write_json_research_market_data_bundle",
    "atomic_write_markdown_research_market_data_bundle",
]
