"""Public API for hunter.open_interest package."""

from __future__ import annotations

from hunter.open_interest.engine import (
    build_open_interest_report,
    build_open_interest_safety_flags,
    build_open_interest_score,
    build_open_interest_universe_summary,
    calculate_oi_change,
    calculate_oi_trend,
    calculate_period_change,
    calculate_price_change,
    classify_funding_context,
    classify_oi_price_positioning,
    has_unsafe_open_interest_content,
    normalized_score,
)
from hunter.open_interest.models import (
    BLOCKED_BY_SAFETY_FLAGS,
    FORBIDDEN_OPEN_INTEREST_TERMS,
    FUNDING_CONTEXT_MISSING,
    HUMAN_RESEARCH_ONLY,
    INPUTS_ALREADY_LOADED,
    INSUFFICIENT_OI_DATA,
    INVALID_OPEN_INTEREST,
    INVALID_PAIR,
    INVALID_PRICE_DATA,
    INVALID_TIMESTAMP,
    NO_ACTION_COMMANDS_EMITTED,
    NO_DATABASE_CONNECTION,
    NO_FILE_READ_IN_ENGINE,
    NO_NETWORK_CONNECTION,
    OPEN_INTEREST_ADVISORY_REASON_CODES,
    OPEN_INTEREST_BLOCKING_REASON_CODES,
    OPEN_INTEREST_INSUFFICIENT_DATA_REASON_CODES,
    OPEN_INTEREST_REASON_CODES,
    OPEN_INTEREST_VERSION,
    PERIOD_DATA_MISSING,
    UNSAFE_OPEN_INTEREST_CONTENT,
    ZERO_DENOMINATOR,
    OpenInterestConfig,
    OpenInterestDataQuality,
    OpenInterestFundingContext,
    OpenInterestInput,
    OpenInterestObservation,
    OpenInterestPeriodChange,
    OpenInterestPositioning,
    OpenInterestReport,
    OpenInterestSafetyFlags,
    OpenInterestScore,
    OpenInterestState,
    OpenInterestTrend,
    OpenInterestUniverseSummary,
)
from hunter.open_interest.writer import (
    DEFAULT_CSV_PATH,
    DEFAULT_JSON_PATH,
    DEFAULT_MD_PATH,
    atomic_write_csv_open_interest_report,
    atomic_write_json_open_interest_report,
    atomic_write_markdown_open_interest_report,
    open_interest_report_to_csv_text,
    open_interest_report_to_dict,
    open_interest_report_to_json_text,
    open_interest_report_to_markdown,
    write_open_interest_report,
)

__all__ = [
    # Constants
    "OPEN_INTEREST_VERSION",
    "FORBIDDEN_OPEN_INTEREST_TERMS",
    # Default paths
    "DEFAULT_JSON_PATH",
    "DEFAULT_CSV_PATH",
    "DEFAULT_MD_PATH",
    # Reason code partitions
    "OPEN_INTEREST_BLOCKING_REASON_CODES",
    "OPEN_INTEREST_INSUFFICIENT_DATA_REASON_CODES",
    "OPEN_INTEREST_ADVISORY_REASON_CODES",
    "OPEN_INTEREST_REASON_CODES",
    # Individual reason codes
    "INVALID_PAIR",
    "INVALID_TIMESTAMP",
    "INVALID_OPEN_INTEREST",
    "INVALID_PRICE_DATA",
    "INSUFFICIENT_OI_DATA",
    "PERIOD_DATA_MISSING",
    "FUNDING_CONTEXT_MISSING",
    "ZERO_DENOMINATOR",
    "UNSAFE_OPEN_INTEREST_CONTENT",
    "BLOCKED_BY_SAFETY_FLAGS",
    "INPUTS_ALREADY_LOADED",
    "NO_ACTION_COMMANDS_EMITTED",
    "HUMAN_RESEARCH_ONLY",
    "NO_NETWORK_CONNECTION",
    "NO_DATABASE_CONNECTION",
    "NO_FILE_READ_IN_ENGINE",
    # Enums
    "OpenInterestState",
    "OpenInterestPositioning",
    "OpenInterestTrend",
    "OpenInterestFundingContext",
    # Models
    "OpenInterestConfig",
    "OpenInterestSafetyFlags",
    "OpenInterestObservation",
    "OpenInterestInput",
    "OpenInterestPeriodChange",
    "OpenInterestScore",
    "OpenInterestDataQuality",
    "OpenInterestUniverseSummary",
    "OpenInterestReport",
    # Engine functions
    "build_open_interest_safety_flags",
    "has_unsafe_open_interest_content",
    "calculate_period_change",
    "calculate_oi_change",
    "calculate_price_change",
    "classify_oi_price_positioning",
    "calculate_oi_trend",
    "classify_funding_context",
    "normalized_score",
    "build_open_interest_score",
    "build_open_interest_universe_summary",
    "build_open_interest_report",
    # Writer functions
    "open_interest_report_to_dict",
    "open_interest_report_to_json_text",
    "open_interest_report_to_csv_text",
    "open_interest_report_to_markdown",
    "atomic_write_json_open_interest_report",
    "atomic_write_csv_open_interest_report",
    "atomic_write_markdown_open_interest_report",
    "write_open_interest_report",
]
