"""Public API for hunter.cross_pack_consistency package.

MVP-36 — Local Research Cross-Pack Consistency Validator.

All exports are deterministic, local, and audit-only. They do not connect to
exchanges, networks, databases, or external services, and do not emit trading or
execution commands. The validator runs only when called by local code or tests;
it is not a scheduler, daemon, server, or background job runner.
"""

from __future__ import annotations

from hunter.cross_pack_consistency.engine import (
    build_cross_pack_consistency_report,
)
from hunter.cross_pack_consistency.models import (
    CONFLICTING_STATE_CLAIM,
    CONSISTENCY_DEGRADED,
    DUPLICATE_ARTIFACT_ID,
    DUPLICATE_PACK_ID,
    DUPLICATE_REQUIREMENT_ID,
    DUPLICATE_SECTION_ID,
    FORBIDDEN_CROSS_PACK_CONSISTENCY_TERMS,
    FORBIDDEN_TERM_PRESENT,
    HUMAN_RESEARCH_ONLY,
    INCOMPATIBLE_VERSION,
    MISSING_EXPECTED_ARTIFACT_REF,
    MISSING_EXPECTED_SECTION_REF,
    MISSING_EXPECTED_REQUIREMENT_REF,
    MISSING_MANUAL_REVIEW,
    MISSING_REQUIRED_PACK,
    NO_ACTION_COMMANDS_EMITTED,
    NO_DAEMON,
    NO_DATABASE,
    NO_EXCHANGE_CONNECTION,
    NO_FILE_INGESTION,
    NO_FREQTRADE_INPUT,
    NO_NETWORK_CONNECTION,
    NO_PRODUCTION_READINESS,
    NO_SCHEDULER,
    NO_WEB_UI,
    NOT_APPLICABLE_RC,
    NOT_TRADING_ADVICE,
    OK,
    ORPHAN_ARTIFACT_REF,
    ORPHAN_REQUIREMENT_REF,
    ORPHAN_SECTION_REF,
    SAFETY_BLOCKED,
    STALE_PACK_DECLARATION,
    UNKNOWN_UPSTREAM_STATE,
    UNSAFE_CONTENT,
    CrossPackArtifactRef,
    CrossPackConsistencyConfig,
    CrossPackConsistencyDataQuality,
    CrossPackConsistencyIssue,
    CrossPackConsistencyIssueType,
    CrossPackConsistencyReasonCode,
    CrossPackConsistencyReport,
    CrossPackConsistencyRule,
    CrossPackConsistencyRuleType,
    CrossPackConsistencySafetyFlags,
    CrossPackConsistencySeverity,
    CrossPackConsistencyState,
    CrossPackDeclaration,
    CrossPackRequirementRef,
    CrossPackSectionRef,
    CrossPackStateClaim,
    CrossPackConsistencyInput,
    has_unsafe_cross_pack_consistency_content,
)

__all__ = [
    "CONFLICTING_STATE_CLAIM",
    "CONSISTENCY_DEGRADED",
    "DUPLICATE_ARTIFACT_ID",
    "DUPLICATE_PACK_ID",
    "DUPLICATE_REQUIREMENT_ID",
    "DUPLICATE_SECTION_ID",
    "FORBIDDEN_CROSS_PACK_CONSISTENCY_TERMS",
    "FORBIDDEN_TERM_PRESENT",
    "HUMAN_RESEARCH_ONLY",
    "INCOMPATIBLE_VERSION",
    "MISSING_EXPECTED_ARTIFACT_REF",
    "MISSING_EXPECTED_REQUIREMENT_REF",
    "MISSING_EXPECTED_SECTION_REF",
    "MISSING_MANUAL_REVIEW",
    "MISSING_REQUIRED_PACK",
    "NO_ACTION_COMMANDS_EMITTED",
    "NO_DAEMON",
    "NO_DATABASE",
    "NO_EXCHANGE_CONNECTION",
    "NO_FILE_INGESTION",
    "NO_FREQTRADE_INPUT",
    "NO_NETWORK_CONNECTION",
    "NO_PRODUCTION_READINESS",
    "NO_SCHEDULER",
    "NO_WEB_UI",
    "NOT_APPLICABLE_RC",
    "NOT_TRADING_ADVICE",
    "OK",
    "ORPHAN_ARTIFACT_REF",
    "ORPHAN_REQUIREMENT_REF",
    "ORPHAN_SECTION_REF",
    "SAFETY_BLOCKED",
    "STALE_PACK_DECLARATION",
    "UNKNOWN_UPSTREAM_STATE",
    "UNSAFE_CONTENT",
    "CrossPackArtifactRef",
    "CrossPackConsistencyConfig",
    "CrossPackConsistencyDataQuality",
    "CrossPackConsistencyIssue",
    "CrossPackConsistencyIssueType",
    "CrossPackConsistencyReasonCode",
    "CrossPackConsistencyReport",
    "CrossPackConsistencyRule",
    "CrossPackConsistencyRuleType",
    "CrossPackConsistencySafetyFlags",
    "CrossPackConsistencySeverity",
    "CrossPackConsistencyState",
    "CrossPackDeclaration",
    "CrossPackRequirementRef",
    "CrossPackSectionRef",
    "CrossPackStateClaim",
    "CrossPackConsistencyInput",
    "build_cross_pack_consistency_report",
    "has_unsafe_cross_pack_consistency_content",
]
