"""Public API for hunter.release_hardening package.

MVP-33 — Local Research Release Hardening / Consistency Audit.

All exports are deterministic, local, and research-only. They do not connect to
exchanges, networks, databases, or external services, and do not emit trading or
execution commands. The audit runs only when called by local code or tests; it is
not a scheduler, daemon, server, or background job runner.
"""

from __future__ import annotations

from hunter.release_hardening.engine import (
    build_release_hardening_report,
    build_release_hardening_safety_flags,
    has_unsafe_release_hardening_content,
)
from hunter.release_hardening.models import (
    CONSISTENCY_DEGRADED,
    FORBIDDEN_RELEASE_HARDENING_TERMS,
    HUMAN_RESEARCH_ONLY,
    MISSING_MARKDOWN_DISCLAIMER,
    MISSING_PUBLIC_EXPORT,
    MISSING_REQUIRED_DECLARATION,
    MISSING_SAFETY_NOTICE,
    MISSING_WRITER_DEFAULT,
    NO_ACTION_COMMANDS_EMITTED,
    NO_DAEMON,
    NO_DATABASE,
    NO_EXCHANGE_CONNECTION,
    NO_FILE_INGESTION,
    NO_FREQTRADE_INPUT,
    NO_NETWORK_CONNECTION,
    NO_SCHEDULER,
    NO_WEB_UI,
    NOT_APPLICABLE_RC,
    NOT_TRADING_ADVICE,
    OK,
    PACKAGE_NOT_PRESENT,
    RELEASE_HARDENING_ADVISORY_REASON_CODES,
    RELEASE_HARDENING_BLOCKING_REASON_CODES,
    RELEASE_HARDENING_REASON_CODES,
    RELEASE_HARDENING_VERSION,
    RESEARCH_ONLY,
    SAFETY_BLOCKED,
    VERSION_INCONSISTENT,
    CompletedAuditPackage,
    PackageDeclaration,
    ReleaseHardeningCheck,
    ReleaseHardeningCheckCategory,
    ReleaseHardeningCheckResult,
    ReleaseHardeningConfig,
    ReleaseHardeningDataQuality,
    ReleaseHardeningInput,
    ReleaseHardeningReasonCode,
    ReleaseHardeningReport,
    ReleaseHardeningSafetyFlags,
    ReleaseHardeningSeverity,
    ReleaseHardeningState,
)

__all__ = [
    "CONSISTENCY_DEGRADED",
    "FORBIDDEN_RELEASE_HARDENING_TERMS",
    "HUMAN_RESEARCH_ONLY",
    "MISSING_MARKDOWN_DISCLAIMER",
    "MISSING_PUBLIC_EXPORT",
    "MISSING_REQUIRED_DECLARATION",
    "MISSING_SAFETY_NOTICE",
    "MISSING_WRITER_DEFAULT",
    "NO_ACTION_COMMANDS_EMITTED",
    "NO_DAEMON",
    "NO_DATABASE",
    "NO_EXCHANGE_CONNECTION",
    "NO_FILE_INGESTION",
    "NO_FREQTRADE_INPUT",
    "NO_NETWORK_CONNECTION",
    "NO_SCHEDULER",
    "NO_WEB_UI",
    "NOT_APPLICABLE_RC",
    "NOT_TRADING_ADVICE",
    "OK",
    "PACKAGE_NOT_PRESENT",
    "RELEASE_HARDENING_ADVISORY_REASON_CODES",
    "RELEASE_HARDENING_BLOCKING_REASON_CODES",
    "RELEASE_HARDENING_REASON_CODES",
    "RELEASE_HARDENING_VERSION",
    "RESEARCH_ONLY",
    "SAFETY_BLOCKED",
    "VERSION_INCONSISTENT",
    "CompletedAuditPackage",
    "PackageDeclaration",
    "ReleaseHardeningCheck",
    "ReleaseHardeningCheckCategory",
    "ReleaseHardeningCheckResult",
    "ReleaseHardeningConfig",
    "ReleaseHardeningDataQuality",
    "ReleaseHardeningInput",
    "ReleaseHardeningReasonCode",
    "ReleaseHardeningReport",
    "ReleaseHardeningSafetyFlags",
    "ReleaseHardeningSeverity",
    "ReleaseHardeningState",
    "build_release_hardening_report",
    "build_release_hardening_safety_flags",
    "has_unsafe_release_hardening_content",
]
