"""Public API for hunter.final_audit_pack package.

MVP-32 — Local Research Final Audit Pack Export.

All exports are deterministic, local, and research-only. They do not connect to
exchanges, networks, databases, or external services, and do not emit trading or
execution commands. The final audit pack runs only when called by local code or
tests; it is not a scheduler, daemon, server, or background job runner.
"""

from __future__ import annotations

from hunter.final_audit_pack.engine import (
    build_final_audit_pack_report,
    build_final_audit_pack_safety_flags,
)
from hunter.final_audit_pack.models import (
    BACKTEST_SECTION_KIND,
    DEFAULT_OPTIONAL_SECTION_KINDS,
    DEFAULT_REQUIRED_SECTION_KINDS,
    DISCOVERY_SECTION_KIND,
    DUPLICATE_SECTION_ID,
    EXPERIMENT_LEDGER_SECTION_KIND,
    FINAL_AUDIT_PACK_ADVISORY_REASON_CODES,
    FINAL_AUDIT_PACK_BLOCKING_REASON_CODES,
    FINAL_AUDIT_PACK_REASON_CODES,
    FINAL_AUDIT_PACK_VERSION,
    FORBIDDEN_FINAL_AUDIT_PACK_TERMS,
    HUMAN_RESEARCH_ONLY,
    INVALID_SECTION,
    MISSING_REQUIRED_FIELDS,
    MISSING_REQUIRED_SECTIONS,
    NO_ACTION_COMMANDS_EMITTED,
    NO_DATABASE,
    NO_DAEMON,
    NO_EXCHANGE_CONNECTION,
    NO_FILE_INGESTION,
    NO_FREQTRADE_INPUT,
    NO_NETWORK_CONNECTION,
    NO_SCHEDULER,
    NO_WEB_UI,
    NOT_TRADING_ADVICE,
    OK,
    PORTFOLIO_CONSTRUCTION_SECTION_KIND,
    REPORTING_CLI_SECTION_KIND,
    RESEARCH_ONLY,
    RUN_ORCHESTRATOR_SECTION_KIND,
    UNSAFE_CONTENT,
    FinalAuditPackArtifact,
    FinalAuditPackConfig,
    FinalAuditPackCompleteness,
    FinalAuditPackDataQuality,
    FinalAuditPackInput,
    FinalAuditPackReasonCode,
    FinalAuditPackReport,
    FinalAuditPackSafetyFlags,
    FinalAuditPackSection,
    FinalAuditPackState,
    has_unsafe_final_audit_pack_content,
)
from hunter.final_audit_pack.writer import (
    DEFAULT_CSV_PATH,
    DEFAULT_JSON_PATH,
    DEFAULT_MD_PATH,
    atomic_write_csv_final_audit_pack_report,
    atomic_write_json_final_audit_pack_report,
    atomic_write_markdown_final_audit_pack_report,
    final_audit_pack_report_to_csv_text,
    final_audit_pack_report_to_dict,
    final_audit_pack_report_to_json_text,
    final_audit_pack_report_to_markdown_text,
    write_final_audit_pack_report,
)

__all__ = [
    "DEFAULT_CSV_PATH",
    "DEFAULT_JSON_PATH",
    "DEFAULT_MD_PATH",
    "BACKTEST_SECTION_KIND",
    "DEFAULT_OPTIONAL_SECTION_KINDS",
    "DEFAULT_REQUIRED_SECTION_KINDS",
    "DISCOVERY_SECTION_KIND",
    "DUPLICATE_SECTION_ID",
    "EXPERIMENT_LEDGER_SECTION_KIND",
    "FINAL_AUDIT_PACK_ADVISORY_REASON_CODES",
    "FINAL_AUDIT_PACK_BLOCKING_REASON_CODES",
    "FINAL_AUDIT_PACK_REASON_CODES",
    "FINAL_AUDIT_PACK_VERSION",
    "FORBIDDEN_FINAL_AUDIT_PACK_TERMS",
    "HUMAN_RESEARCH_ONLY",
    "INVALID_SECTION",
    "MISSING_REQUIRED_FIELDS",
    "MISSING_REQUIRED_SECTIONS",
    "NO_ACTION_COMMANDS_EMITTED",
    "NO_DATABASE",
    "NO_DAEMON",
    "NO_EXCHANGE_CONNECTION",
    "NO_FILE_INGESTION",
    "NO_FREQTRADE_INPUT",
    "NO_NETWORK_CONNECTION",
    "NO_SCHEDULER",
    "NO_WEB_UI",
    "NOT_TRADING_ADVICE",
    "OK",
    "PORTFOLIO_CONSTRUCTION_SECTION_KIND",
    "REPORTING_CLI_SECTION_KIND",
    "RESEARCH_ONLY",
    "RUN_ORCHESTRATOR_SECTION_KIND",
    "UNSAFE_CONTENT",
    "FinalAuditPackArtifact",
    "FinalAuditPackConfig",
    "FinalAuditPackCompleteness",
    "FinalAuditPackDataQuality",
    "FinalAuditPackInput",
    "FinalAuditPackReasonCode",
    "FinalAuditPackReport",
    "FinalAuditPackSafetyFlags",
    "FinalAuditPackSection",
    "FinalAuditPackState",
    "atomic_write_csv_final_audit_pack_report",
    "atomic_write_json_final_audit_pack_report",
    "atomic_write_markdown_final_audit_pack_report",
    "build_final_audit_pack_report",
    "build_final_audit_pack_safety_flags",
    "final_audit_pack_report_to_csv_text",
    "final_audit_pack_report_to_dict",
    "final_audit_pack_report_to_json_text",
    "final_audit_pack_report_to_markdown_text",
    "has_unsafe_final_audit_pack_content",
    "write_final_audit_pack_report",
]
